config/routes.rb
Rails.application.routes.draw do
  resources :themes

  resources :rounds, except: %i[edit update create] do
    member do
      get :result
    end
  end
  resources :questions do
    member do
      get :check
    end
  end
  root 'main#index'
  devise_for :users

  resources :users, only: %i[index edit update show]

  get :audit, to: 'main#audit'
end

app/models/question.rb
class Question < ApplicationRecord
  audited

  belongs_to :author, class_name:    'User',
                      foreign_key:   'author_id'
  belongs_to :theme,  counter_cache: true

  has_many :answers, inverse_of: :question, dependent: :destroy
  has_many :results
  has_many :rounds, through: :results

  validates :title, uniqueness: true,
                    presence:   true

  validates :answers, length: { is: 4, message: 'must be four' }

  validate :check_correct_flag

  accepts_nested_attributes_for :answers, reject_if: :all_blank

  def current_answer_id
    answers.where(correct: true).first.id
  end

  private

    # check if correct flag not choose
    #
    def check_correct_flag
      errors.add(:correct, I18n.t('questions.flag_must_exist')) unless self.answers.map(&:correct).count(true) == 1
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_question, only: %i[show edit update destroy check]
  after_action :verify_authorized

  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true)

    @pagy, @questions = pagy(@questions.includes(:theme, :author).order(created_at: :desc))
    authorize @questions
  end

  def show
    authorize @question
  end

  def new
    @question = Question.new
    authorize @question
    4.times { @question.answers.build }
  end

  def check
    authorize @question
    @answer_id = params[:answer_id]
    @round = Round.find(params[:round_id])
    @result = @round.make_result!(@question, @answer_id)# if @round.results.where(question_id: @question, answer_id: @answer_id).empty?
  end

  def edit
    authorize @question
  end

  def create
    @question = Question.new(question_params)
    authorize @question

    @question.author = current_user

    @question.audit_comment = t('audit.comments.new_question', theme: @question.theme&.title, title: @question.title)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: t('flash.was_created', item: Question.model_name.human) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @question
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: t('flash.was_updated', item: Question.model_name.human) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @question

    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: t('flash.was_destroyed', item: Question.model_name.human)  }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :theme_id,  answers_attributes: [:id, :title, :correct])
    end
end

app/views/questions/_form.html.haml
.row
  .col.col-12
    %h1= formtitle

    = form_with(model: question, local: true) do |form|
      = render 'application/error', object: question

      .field
        = form.label :title
        = form.text_area :title

      .field
        = form.label :theme_id
        = form.select :theme_id, Theme.order(:title).map{ |theme| [theme.title, theme.id] }, { include_blank: t('actions.select') }
        .form-helptext
          = link_to t('themes.add_new'), '#add_theme', id: 'add-theme', onclick: "getThemeForm(this)"

      = form.fields_for :answers do |a|
        .field
          = a.label :title, t('questions.answer', index: a.options[:child_index] + 1)
          .row
            .col-11
              = a.text_field :title
            .col-1
              = a.check_box :correct, class: 'right-checkbox answerCheckbox', onclick: "selectOnlyOneCheckbox(this)"
      .actions
        = form.submit class: 'btn'
        .float-right
          = link_to t('actions.back'), questions_path, class: 'btn btn-outline'

    = render 'themes/remote_form'

app/views/questions/_progress.html.haml
= results.pluck(:success).each do |result|
  - if result == false
    .progress-bar-failed(style="width:#{part}%")><
  - else
    .progress-bar-success(style="width:#{part}%")><

app/views/questions/_question.html.haml
- if @pagy.next
  - next_url = round_path(@round)
  - next_title = t('actions.next_html')
- else
  - next_url = result_round_path(@round)
  - next_title = t('results.show_html')

.row
  .col.col-12
    #progress.progress
      = render 'questions/progress', results: @round.results, part: @round.questions_part

  .col.col-12.text-muted.text-right
    = [Question.human_attribute_name(:author).downcase, question.author.login].join(': ')

  .col.col-12
    %h2.text-center.question-title
      %span.text-muted Вопрос № #{@round.questions.count + 1}.
      #{question.title}

  .col.col-12
    #timer.timer= Round::LIMIT_TIME

.row
  - question.answers.shuffle.each do |answer|
    .col.col-12
      = link_to answer.title,
        check_question_path(question, answer_id: answer.id, round_id: @round.id),
        remote: true,
        class: 'button mb-2 btn-answer',
        id: dom_id(answer)

  = link_to 'empty question',
    check_question_path(question, round_id: @round.id),
    remote: true,
    class: 'd-none',
    id: 'empty-result-button'

.row
  .col.col-12.text-center
    = link_to next_title, next_url, class: 'btn d-none', id: 'next-button', remote: true

app/views/questions/_search_form.html.haml
= search_form_for q do |f|
  = f.search_field :title_or_theme_title_or_author_login_cont, placeholder: t('questions.search_placeholder')
  = f.submit class: 'btn btn-md'

app/views/questions/check.js.erb
// mark background for current button
//
var button = document.getElementById('answer_' + <%= @answer_id %>);
var current_button = document.getElementById('answer_' + <%= @question.current_answer_id %>);
if (<%= @result %> == false) {
  var current_button = document.getElementById('answer_' + <%= @question.current_answer_id %>);

  button.style.backgroundColor = "red";
  current_button.style.backgroundColor = "green";
} else {
  button.style.backgroundColor = "green";
}

// disable href for all links
//
var buttons = document.getElementsByClassName("button");
for (var i = 0, len = buttons.length; i < len; i++) {
    var button = buttons[i];
    button.href="javascript:;";
}

// update progress
//
var progress_line = document.getElementById("progress");
progress_line.innerHTML = "<%= render 'questions/progress', results: @round.results, part: @round.questions_part%>";


// Set a fake timeout to get the highest timeout id
// need to disable timer
//
var highestTimeoutId = setTimeout(";");
for (var i = 0 ; i < highestTimeoutId ; i++) {
    clearTimeout(i); 
}

// show next button
//
var next_button = document.getElementById('next-button');
next_button.classList.remove('d-none');

app/views/questions/edit.html.haml
= render 'questions/form', question: @question, formtitle: t('questions.edit_title')

app/views/questions/index.html.haml
.row.mb-3
  .col.col-6
    - if policy(Question).new?
      = link_to t('questions.add'), new_question_path, class: 'btn btn-outline btn-sm'
    = link_to t('themes.title'), themes_path, class: 'btn btn-outline btn-sm ml-3'
  .col.col-6.text-right
    = render 'questions/search_form', q: @q

.row
  .col.col-12
    - if @questions.any?
      .pb-2.text-right= raw pagy_nav(@pagy)
      %table.table
        %thead
          %tr
            %th
              = sort_link(@q, :title, Question.human_attribute_name(:title))
            %th
              = sort_link(@q, :theme_title, Theme.model_name.human.capitalize)
            %th
              = sort_link(@q, :author_login, Question.human_attribute_name(:author))
            %th
              = sort_link(@q, :created_at, t('fields.created_at'))
            %th
        %tbody
          - @questions.each do |question|
            %tr
              %td= link_to question.title, question
              %td= question.theme.title
              %td= question.author.login
              %td= rus_date(question.created_at)
              - if policy(question).edit?
                %td
                  %ul.tooltip
                    %li
                      %a &#9881;
                      %ul
                        %li= link_to t('actions.edit'), edit_question_path(question)
                        %li= link_to t('actions.del'), question, method: :delete, data: { confirm: t('actions.sure') }
      .pt-2.text-right= raw pagy_nav(@pagy)

    - else
      .empty-block
        = t('titles.empty')

app/views/questions/new.html.haml
= render 'questions/form', question: @question, formtitle: t('questions.new_title')

app/views/questions/show.html.haml
.row
  .col.col-12
    %h1= @question.title

    = @question.theme.title
  .col.col-12.text-right
    %strong
    = Question.human_attribute_name(:author)
    = @question.author.login

- @question.answers.each do |answer|
  .row
    .col.col-12
      .button.mb-2.btn-answer= answer.title