config/routes.rb
Rails.application.routes.draw do
  resources :themes

  resources :rounds, except: %i[edit update create] do
    member do
      get :result
    end
  end
  resources :questions do
    member do
      get :check
    end
  end
  root 'main#index'
  devise_for :users

  resources :users, only: %i[index edit update show]

  get :audit, to: 'main#audit'
end

app/models/theme.rb
class Theme < ApplicationRecord
  audited

  validates  :title, uniqueness: true,
                     presence:   true

  has_many :questions, dependent: :destroy

  def to_param
    "#{id}-#{title.parameterize}"
  end

end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_theme,          only:   %i[show edit update destroy check]

  after_action :verify_authorized

  def index
    authorize Theme
    @q = Theme.ransack(params[:q])
    @themes = @q.result(distinct: true)

    @pagy, @themes = pagy(@themes.order(title: :desc))
  end

  def show
    authorize @theme
  end

  def new
    @theme = Theme.new
    authorize @theme
  end

  def create
    @theme = Theme.new(theme_params)
    authorize @theme

    @theme.audit_comment = t('audit.comments.theme_name', theme: @theme.title)

    respond_to do |format|
      if @theme.save
        format.html { redirect_to themes_url, notice: t('flash.was_created', item: Theme.model_name.human) }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
    authorize @theme
  end

  def update
    authorize @theme
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to themes_url, notice: t('flash.was_updated', item: Theme.model_name.human) }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @theme

    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: t('flash.was_destroyed', item: Theme.model_name.human)  }
    end
  end



  private
    def set_theme
      @theme = Theme.find(params[:id])
    end


    def theme_params
      params.require(:theme).permit(:title)
    end
end

app/views/themes/_form.html.haml
.row
  .col.col-12
    %h1= formtitle

    = form_with(model: theme, local: true) do |form|
      = render 'application/error', object: theme

      .field
        = form.label :title
        = form.text_field :title

      .actions
        = form.submit t('actions.save'), class: 'btn'
        .float-right
          = link_to t('actions.back'), themes_path, class: 'btn btn-outline'

app/views/themes/_remote_form.html.haml
#theme_modal.modal.d-none
  .modal_dialog
    %header.modal_header
      %h2= t('themes.new_title')
    .modal_content
      #theme_errors
      = form_with(model: Theme.new, id: 'new_theme_form') do |f|
        = f.label :title
        = f.text_field :title
        .modal-actions
          = f.submit t('actions.add'), class: 'btn'
          .float-right
            .btn.btn-outline#modal_close
              = t('actions.close')

app/views/themes/_search_form.html.haml
= search_form_for q do |f|
  = f.search_field :title_cont, placeholder: t('themes.search_placeholder')
  = f.submit class: 'btn btn-md'

app/views/themes/create.js.erb
<% if @theme.errors.any? %>
  themeErrors = document.getElementById('theme_errors');
  // Remove old errors
  themeErrors.innerHTML = "<%= j render('application/error', object: @theme) %>";
<% else %>
  questionSelect = document.getElementById('question_theme_id');
  questionSelect.options[questionSelect.options.length] = new Option('<%= @theme.title %>', '<%= @theme.id %>');

  themeModal = document.getElementById('theme_modal');
  themeModal.classList.add('d-none');

  themeForm = document.getElementById('new_theme_form');
  themeForm.reset();
<% end %>

app/views/themes/edit.html.haml
= render 'themes/form', theme: @theme, formtitle: t('themes.edit_title')

app/views/themes/index.html.haml
.row
  .col.col-6
    - if policy(Theme).new?
      = link_to t('themes.add'), new_theme_path, class: 'btn btn-outline btn-sm mb-2'
  .col.col-6.text-right
    = render 'themes/search_form', q: @q

.row
  .col.col-12
    - if @themes.any?
      .pb-2.text-right= raw pagy_nav(@pagy)
      %table.table
        %thead
          %tr
            %th
              = sort_link @q, :title, Theme.human_attribute_name(:title)
            %th
              = sort_link @q, :questions_count, t('themes.questions_count'), default_order: :desc
            %th
        %tbody
          - @themes.each do |theme|
            %tr
              %td= link_to theme.title, theme
              %td= theme.questions_count
              - if policy(theme).edit?
                %td
                  %ul.tooltip
                    %li
                      %a &#9881;
                      %ul
                        %li= link_to t('actions.edit'), edit_theme_path(theme)
                        %li= link_to t('actions.del'), theme, method: :delete, data: { confirm: t('actions.sure') }
      .pt-2.text-right= raw pagy_nav(@pagy)

    - else
      .empty-block
        = t('titles.empty')

app/views/themes/new.html.haml
= render 'themes/form', theme: @theme, formtitle: t('themes.new_title')

app/views/themes/show.html.haml
= render 'rounds/single_round',
    theme_title: @theme.title,
    questions_count: @theme.questions_count do

  - if @theme.questions_count > 0
    = link_to new_round_path(theme_id: @theme), class: 'btn', remote: true do
      = t('actions.start')
  - else
    .lead.text-muted
      = t('themes.empty_questions')